# defaults are 0, YAML reads as int, otherwise 'None' will be read as string
basein: C:/Users/rmcma/Data/2019_TUD_floc_data/raw/2019-12-11_PoH_data
baseout: C:/Users/rmcma/Desktop/safas-update
input: C:/Users/rmcma/Data/2019_TUD_floc_data/raw/2019-12-11_PoH_data/part1_KH2-RT2-SW2-RV2/000_KH2_01_DII12002_high_graylevel_01.avi
output: 0

improcess:
  mode: find-all
  running: False
  fps: None
  pixel_size: 8.6 # microns
  size: None   # dimensions of image. [height, width, length]
  max_track_len: 40
  min_track_len: 3
  max_object_angle: 30
  n_frames: 40
  filter: sobel_focus
  kwargs:
    pre_filter: True
    focus_filter: True
    clearborder_filter: True
    img_thresh: 130
    edge_thresh: 80
    edge_dist: 1

save:
  confirm: True # confirm save settings each time
  filename: props_frame_%05d.xlsx # name of object properties files
  save_frames: False
  save_object_images: True
  clear: True # default clear after save

matcher:
  error_threshold: 100
  distance: 1
  area: 1
  squared: False

viewer:
  pos: [750, 50]
  scale: 0.5
