# defaults are 0, YAML reads as int, otherwise 'None' will be read as string
basein: C:\Users\rmcma\Desktop
baseout: C:\\Users\\rmcma\\Desktop\\floc_analysis
input: 0
output: 0

improcess:
  mode: find-all
  running: False
  fps: None
  pixel_size: 8.6 # microns
  size: None   # dimensions of image. [height, width, length]
  max_track_len: 30
  min_track_len: 3
  max_object_angle: 50
  n_frames: 30
  filter: sobel_focus
  kwargs:
    img_thresh: 120
    edge_thresh: 90
    apply_focus_filter: True
    apply_clear_edge_filter: True
    contour_thickness: 1


save:
  confirm: True # confirm save settings each time
  filename: props_frame_%05d.xlsx # name of object properties files
  save_frames: False
  save_object_images: True
  clear: True # default clear after save

matcher:
  error_threshold: 500
  distance: 1
  area: 1
  squared: False

viewer:
  pos: [750, 50]
  scale: 0.5
